### ISSUE TITLE
Getting error while running app chrome app

### ISSUE THREAD

**Issue by chirag-metacube** [koush/electron-chrome#13]
I tried to convert my chrome into electron app, but while converson it opens 2-3 windows of cmd and nothing happens next,
![image](https://cloud.githubusercontent.com/assets/19548829/18780295/6e8f3dfc-819a-11e6-8e80-024633b9676b.png)
![image](https://cloud.githubusercontent.com/assets/19548829/18780317/9829cc2c-819a-11e6-979a-727ded2e4bac.png)

**Comment by koush** [comment]
Will check. I only just started verifying Windows functionality.

**Comment by koush** [comment]
windows works, looks like you were hitting a missing method in AppWindow.maximize. I have since implemented it.
