### ISSUE TITLE
Electron fails to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by SillonBono** [koush/electron-chrome#17]
Ubuntu 16.04

apt-get install npm
git clone https://github.com/koush/electron-chrome.git
cd electron-chrome
npm install

npm WARN ElectronChrome@0.1.0 No repository field.
npm WARN ElectronChrome@0.1.0 No license field.
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron-prebuilt@1.4.12 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.4.12 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/electron/electron-chrome/npm-debug.log

[npm-debug.txt](https://github.com/koush/electron-chrome/files/655299/npm-debug.txt)

**Comment by SillonBono** [comment]
Solution:

As root run:

cd ~
mkdir electron
cd electron
apt-get install npm
ln -s /usr/bin/nodejs /usr/bin/node
git clone https://github.com/koush/electron-chrome.git
npm install

electron --enable-logging . --app-id=gidgenkbbabolejbgbpnhbimgjbffefm

**Comment by koush** [comment]
please report this on the electron project. that is upstream.
