### ISSUE TITLE
-bash: electron: command not found

### ISSUE THREAD

**Issue by dsemaya** [koush/electron-chrome#18]
I followed these instructions:

> Install:
> 
> > git clone https://github.com/koush/electron-chrome.git
> > cd electron-chrome
> > npm install
> 
> Run:
>  
> > electron --enable-logging . --app-dir=/path/to/chrome-app/

And I get:
> -bash: electron: command not found

Do I need to install Electron first?

**Comment by slackr** [comment]
You'll need to install electron, either binary in global path or via npm

if npm:

electron-chrome$ npm install electron
electron-chrome/$ ./node_modules/.bin/electron . --enable-logging --app-dir=/path/to/app
