### ISSUE TITLE
Distribute app as executable

### ISSUE THREAD

**Issue by McGiverGim** [koush/electron-chrome#23]
Hi! I don't know if this is the place to ask for help...

I want to distribute an app in the chrome store, but I don't want that the user needs to put commands or install packages. I want to give them an executable (or an install program) with all stuff and when the user executes it, the app will be downloaded from the chrome store and executed. I don't know if the program is cached then to access in local until there's a new version.

I've seen this project, and it seems to make something similar. Can it be used to accomplish that? I've made my program compatible with Electron, so this part is done.

Thanks!

**Comment by koush** [comment]
uh, check the chrome store apis.
