### ISSUE TITLE
npm install fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by autonomousapps** [koush/electron-chrome#24]
I installed npm with `sudo apt-get install npm`. I then ran the command: `npm install` in the `electron-chrome directory`. It failed, and suggested I include this log in a bug report:
[npm-debug.txt](https://github.com/koush/electron-chrome/files/980150/npm-debug.txt)

Note: Github wouldn't let me upload it with the .log extension, so I changed it to .txt.

I assume the error has to do with apt installing an older version of npm. Since this is outside my domain, could you suggest how to install a newer version?

**Comment by MTRNord** [comment]
Try to follow this install guide on nodejs. it installs the newest nodejs and npm version https://nodejs.org/en/download/package-manager/

**Comment by autonomousapps** [comment]
Works perfectly! Thanks.
