### ISSUE TITLE
identity

### ISSUE THREAD

**Issue by NdYAG** [koush/electron-chrome#25]
https://github.com/koush/electron-chrome/blob/master/chrome/api/chrome-identity/index.js#L215

It seems that the code here doesn't work for 3rd party OAuth identification

Maybe a better workaround is to use `BrowserWindow` to open the url.

```js
const authWindow = new BrowserWindow(windowParams)
authWindow.loadURL(url)
authWindow.show()
safeRegister(remote.getCurrentWindow(), authWindow.webContents, (e, url) => {
  authCallback(null, url)
  setImmediate(function () {
    authWindow.close()
  })
}, 'will-navigate')
// register the same handler for `did-get-redirect-request` event
```

**Comment by koush** [comment]
can try removing that !opt.oob bit altogether and seeing if the other code works. that's what's used for google auth flow.

https://github.com/koush/electron-chrome/blob/master/chrome/api/chrome-identity/index.js#L210

**Comment by NdYAG** [comment]
Hi @koush,
It's OK. I find out that the workflow of each 3rd party might have minor differences. 
It might be better to leave this to developers than implementing a strategy for every one
