### ISSUE TITLE
Windows 10 cmd issue

### ISSUE THREAD

**Issue by petrk94** [koush/electron-chrome#3]
I try to run electron in the cmd, but it just open the electron builder window and telling me to drag the app in it, but what it need? 
When I used 
`electron.exe --enable-logging . --app-id=gidgenkbbabolejbgbpnhbimgjbffefm`
then I just got an error.
Anyone know why?

**Comment by warrickhunter** [comment]
I was able to run it from the electron-chrome directory in Windows 10 using:
`"./node_modules/.bin/electron" --enable-logging . --app-id=gidgenkbbabolejbgbpnhbimgjbffefm`

**Comment by koush** [comment]
should be fixed
