### ISSUE TITLE
Local build & CORS issue

### ISSUE THREAD

**Issue by tvvignesh** [koush/electron-chrome#5]
If I try to execute my app from my pc (not from store), I get this error:

`"./node_modules/.bin/electron" --enable-logging . --app-dir= "/home/vignesh/OFFICIAL/workspace/chrome/app"
[9609:0830/170753:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
using chrome runtime 1.0.0.3
starting chrome app at /home/vignesh/OFFICIAL/workspace/chrome/app
no key in manifest, please provide an --app-id
`

If I try to execute the app from the store, it runs and when I do signin in my app (XMLHttpRequest),

`"./node_modules/.bin/electron" --enable-logging . --app-id="dlpjljhdpgignbioilieekedeodphhfh"`

 I get this error:

`[10230:0830/173927:INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://empsense.ramco.com/auth/signin. Response for preflight has invalid HTTP status code 404", source: chrome-extension://dlpjljhdpgignbioilieekedeodphhfh/index.html#/app/register (0)
`

But the thing is the app works well as a chrome app (without any cors issue)

Any help is appreciated.
Thanks in advance.

**Comment by koush** [comment]
i'll give it a shot

**Comment by koush** [comment]
Well, https://empsense.ramco.com/auth/signin is legitimately a 404.

**Comment by tvvignesh** [comment]
I am just wondering why this occurs cause the same error does not come up in chrome APP and it works perfectly. It throws a 404 only when a request is sent to that URL without a token.

Dont break your head though, I ended up making a separate electron build.

PS: Is there anyway that I can use chrome.gcm API or any GCM/FCM notification in electron app? It works in chrome app.
