### ISSUE TITLE
chrome.sockets api

### ISSUE THREAD

**Issue by ethanaobrien** [koush/electron-chrome#60]
Is the `chrome.sockets` api going to be implemented? You said you do not plan to implement `chrome.socket` but this is different from `chrome.sockets`. If we could get `chrome.sockets` available, then we could use this tool to convert Web Server for Chrome (Which I think is the best and easiest web server)

**Comment by koush** [comment]
The chrome APIs are dead too now, and there's no value in continuing this project.
